---
- name: variable behaviour - original
  import_tasks: tasks/original.yml
  when: list_appport == "9090"

- name: variable behaviour - default
  import_tasks: tasks/default.yml
  when: list_appport == "9999"

- name: variable behaviour - SOmething else
  import_tasks: tasks/else.yml
  when:
    - list_appport != "9999"
    - list_appport != "9090"
