---
- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"
    mode: 0766

- name: "Insert custom fact file"
  copy:
    src: files/local.fact
    dest: /etc/ansible/facts.d/local.fact
    mode: 0644

- name: "Insert custom fact script"
  copy:
    src: files/ec2_info.sh
    dest: /tmp/ec2_info.sh
    mode: 0755

- name: add Instance facts
  shell: /tmp/ec2_info.sh
  

- name: local facts
  debug: var=ansible_local
  notify:
  - reload facts

- name: reload facts
  setup: filter=ansible_local
