---

- name: Add facts to a variable
  setup:
  register: setupvar

- name: create facts file DIR
  file:
    path: /tmp/facts
    state: directory

- name: Store facts indexed by hostname in /tmp/facts
  copy:
    content: '{{ setupvar }}'
    dest: /tmp/facts/{{ ansible_hostname }}.yaml
